// Chapter-specific collectible art. All 38 chapters now have dedicated relic art.
export const ARTIFACT_IMAGES={
  1:'old_journal.png',
  2:'forest_compass.png',
  3:'forest_key.png',
  4:'miner_lantern.png',
  5:'diving_mask.png',
  6:'forest_medallion.png',
  7:'spyglass.png',
  8:'iron_seal.png',
  9:'forest_map.png',
  10:'ocean_heart.png',
  11:'sun_hourglass.png',
  12:'forest_vessel.png',
  13:'geologist_hammer.png',
  14:'sun_disc.png',
  15:'merchant_token.png',
  16:'forest_amber.png',
  17:'obsidian_sample.png',
  18:'magma_crystal.png',
  19:'copper_seal.png',
  20:'aeronaut_wings.png',
  21:'sky_compass.png',
  22:'astrolabe.png',
  23:'wanderer_weathervane.png',
  24:'ice_crampons.png',
  25:'snow_prism.png',
  26:'ice_crystal.png',
  27:'glowing_sphere.png',
  28:'winding_key.png',
  29:'expedition_flag.png',
  30:'master_key.png',
  31:'gold_coin.png',
  32:'ancient_folio.png',
  33:'chronometer.png',
  34:'explorer_prism.png',
  35:'portrait_relief.png',
  36:'keeper_crown.png',
  37:'legend_chest.png',
  38:'seeker_legend.png',
};
export const artifactImage=id=>ARTIFACT_IMAGES[id]?`./assets/UI/artifacts/${ARTIFACT_IMAGES[id]}`:null;
export const artifactImageMap=()=>({...ARTIFACT_IMAGES});
