import {artifactAsset,uiAsset} from './asset-manifest.js';
import {ABILITIES,companionBondText,companionUnlockText} from './companions.js';
import {CAPTAINS,captainIsUnlocked} from './captains.js';
import {CHAPTERS,COMPANIONS} from './content.js';
import {dateKey,previousDay,dailyRoute,starsTotal} from './core.js';
import {endlessRank} from './endless-meta.js';
import {icon,shopIcon} from './icons.js';
import {SHOP_ITEMS,GOALS,weekKey,goalValue as economyGoalValue,dailyGiftOffer,ensureDailyState,ensureWeeklyState,buyShopItem,claimGoal} from './economy.js';

export function createMetaScreens(ctx){
 const {app,state,setScreen,getLevels,getConfig,econ,weeklyCfg,rewardedCfg,rewardedRemaining,store,platform,analytics,leaveScreen,setBackground,topbar,btn,iconBtn,coinPill,chapterFor,chapterImage,chapterWideImage,petImage,petCard,captainTitle,captainMotto,portraitIcon,captainAvatar,toast,save,modal,commerceAvailable,commerceProduct,commerceBuy,commerceStatus,commerceRetry,escapeHTML,startLevel}=ctx;

 function home(){leaveScreen();ensureDaily();setScreen('home');setBackground();const levels=getLevels(),s=state(),id=ctx.nextLevel(s),chapter=chapterFor(id),completedIn=s.completed.filter(v=>v>=chapter.startLevel+1&&v<=chapter.startLevel+8).length,all=s.completed.length===levels.length;
  app.innerHTML=`<section class="screen home"><header class="topbar"><div class="brand-mark">${icon('journey')}<span>Слова: Забытая Экспедиция</span></div><div class="row">${coinPill()}${iconBtn('profile','Профиль капитана','user')}${iconBtn('settings','Настройки','settings')}</div></header>
  <div class="home-body"><div class="hero-copy"><p class="eyebrow">Маленькое открытие каждый день</p><h1>Слова открывают<br><span>целые миры.</span></h1><p class="hero-subtitle">Собирайте слова. Находите сокровища.<br>Отправляйтесь туда, где ещё не бывали.</p><div class="hero-stat"><div><strong>38</strong><span>УДИВИТЕЛЬНЫХ МЕСТ</span></div><div><strong>304</strong><span>КРОССВОРДА</span></div><div><strong>∞</strong><span>ВРЕМЕНИ ПОДУМАТЬ</span></div></div></div>
  <div class="journey-card"><div class="chapter-preview" style="background-image:url('${chapterWideImage(chapter.id-1)}')"><span class="chip">Глава ${chapter.id} из 38</span></div><p class="eyebrow">${all?'Большое путешествие завершено':'Ваше путешествие'}</p><h2>${chapter.title}</h2><div class="row between small"><span>${all?'Все места открыты':`Уровень ${id} из 304`}</span><span>${completedIn}/8</span></div><div class="progress-track journey-progress"><div class="progress-fill" style="width:${completedIn/8*100}%"></div></div><p class="small journey-discovery">${all?'Все находки собраны':completedIn===0?'Первая находка — после 8 уровней':`До находки главы: ${8-completedIn} уров.`}</p>${btn(all?'endless':'continue',all?'Бесконечная экспедиция':s.completed.length?'Продолжить путь':'Начать путешествие','arrow','primary wide')}<div class="row between"><span class="small">${icon('star','gold')} ${starsTotal(s)} звёзд</span>${btn('map','Карта','map','secondary compact-button')}</div></div></div>
  <nav class="home-bottom" aria-label="Режимы и коллекции"><button class="feature-button feature-primary" data-action="daily">${icon('daily')}<div><strong>Маршрут дня</strong><span>3 этапа · ${s.daily.claimed?'завершён':`награда ${econ().dailyCoins} монет`}</span></div></button><button class="feature-button" data-action="album">${icon('journal')}<div><strong>Дневник и спутники</strong><span>${CHAPTERS.filter(c=>Array.from({length:8},(_,i)=>c.startLevel+i+1).every(level=>s.completed.includes(level))).length}/38 артефактов · ${s.pets.length}/12 друзей</span></div></button><button class="feature-button" data-action="pets">${icon('companions')}<div><strong>Спутники</strong><span>${s.pets.length}/12 друзей</span></div></button><button class="feature-button" data-action="goals">${icon('goals')}<div><strong>Цели экспедиции</strong><span>Прогресс и награды</span></div></button>${all?`<button class="feature-button" data-action="endless">${icon('endless')}<div><strong>Бесконечная экспедиция</strong><span>Лучший этап: ${s.endless.best}</span></div></button>`:''}<button class="feature-button feature-secondary" data-action="shop">${icon('shop')}<div><strong>Магазин</strong><span>Оформление экспедиции</span></div></button></nav>${s.inventory.includes('camp-lantern')?`<div class="camp-decoration">${icon('lantern')}<span>Фонарь вашего лагеря</span></div>`:''}<button class="weekly-fab" data-action="weekly">${icon('weekly')}<span>Экспедиция недели</span></button><p class="home-caption">БЕЗ ТАЙМЕРА · В СВОЁМ РИТМЕ</p></section>`;
 }

 function mapPage(){leaveScreen();setScreen('map');setBackground(1);const s=state(),unlocked=ctx.nextLevel(s);app.innerHTML=`<section class="screen scroll-page map-screen">${topbar('Карта путешествия')}<div class="page-title"><p class="eyebrow">От первого костра до края света</p><h1>Впереди — целый мир</h1><p class="small">${s.completed.length} из 304 уровней · ${starsTotal(s)} звёзд</p></div><div class="map-chapters">${CHAPTERS.map((c,index)=>{const count=s.completed.filter(v=>v>c.startLevel&&v<=c.startLevel+8).length,locked=c.startLevel+1>unlocked;return `<article class="chapter-card ${locked?'locked':''}" id="chapter-${c.id}"><img class="chapter-art" src="${chapterWideImage(index)}" alt="" loading="lazy"><div class="chapter-info"><div class="row between"><p class="eyebrow">ГЛАВА ${c.id}</p><span class="small">${count}/8</span></div><h3 class="chapter-title">${c.title}</h3><div class="chapter-find ${count===8?'collected':''}"><img src="${artifactAsset(c.id)}" alt="" loading="lazy" width="52" height="52"><div><span class="small">${count===8?'В вашем дневнике':locked?'Будущая находка':'Награда за главу'}</span><b>${c.artifact}</b></div>${count===8?icon('complete'):''}</div><div class="level-nodes">${Array.from({length:8},(_,i)=>{const id=c.startLevel+i+1,done=s.completed.includes(id);return `<button class="level-node ${done?'done':id===unlocked?'current':''}" data-action="level" data-id="${id}" ${id>unlocked?'disabled':''} aria-label="Уровень ${id}${done?', пройден':''}">${id>unlocked?icon('lock'):id}${done?`<span class="level-stars">${'★'.repeat(s.stars[id]||1)}</span>`:''}</button>`;}).join('')}</div></div></article>`;}).join('')}</div></section>`;
  document.querySelector(`#chapter-${chapterFor(unlocked).id}`)?.scrollIntoView({block:'center'});
 }

 function albumPage(){leaveScreen();setScreen('album');setBackground(5);const s=state(),unlocked=CHAPTERS.filter(c=>Array.from({length:8},(_,i)=>c.startLevel+i+1).every(id=>s.completed.includes(id)));app.innerHTML=`<section class="screen scroll-page album-screen">${topbar('Мои открытия')}<div class="page-title"><p class="eyebrow">История, которую собираете вы</p><h1>Дневник искателя</h1><div class="row between"><p class="small">Найдено ${unlocked.length} из 38 артефактов</p>${btn('pets','Спутники','companions','secondary')}</div></div><div class="collection-grid">${CHAPTERS.map((c,i)=>{const open=unlocked.includes(c),art=artifactAsset(c.id),src=art||uiAsset('reward_artifact.png'),kind=art?'artifact-cutout':'artifact-generic';return `<button class="collection-card ${open?'':'locked'}" data-action="artifact" data-id="${c.id}"><img class="${kind}" src="${src}" alt="" loading="lazy"><span class="caption"><b>${open?c.artifact:icon('lock')+' '+c.title}</b><span class="small">${open?'Прочитать страницу':'Пройдите главу '+c.id}</span></span></button>`;}).join('')}</div></section>`;}

 function artifact(id){const c=CHAPTERS[id-1];if(!c)return;const open=Array.from({length:8},(_,i)=>c.startLevel+i+1).every(n=>state().completed.includes(n));if(!open){toast(`Пройдите 8 уровней главы «${c.title}»`);return;}const art=artifactAsset(id),src=art||uiAsset('reward_artifact.png');modal('artifact',`<div class="surface-body"><div class="artifact-showcase ${art?'has-cutout':'has-generic'}"><img class="album-preview ${art?'artifact-cutout':'artifact-generic'}" src="${src}" alt="${c.artifact}"></div><p class="eyebrow">Страница ${id} · ${c.title}</p><h2>${c.artifact}</h2><p>${c.storyText}</p></div><div class="surface-footer">${btn('close','Продолжить открытия','arrow','primary wide')}</div>`,{cls:'surface panel-md'});}

 function petsPage(){analytics.send('companion_seen',{owned:state().pets.length,active:state().activePet||null});const prevScroll=document.querySelector('.pets-screen')?.scrollTop||0;leaveScreen();setScreen('pets');setBackground(5);const s=state(),config=getConfig(),memoryLabel=v=>{if(v.startsWith('chapter:'))return `Глава ${v.slice(8)} отмечена`;if(v.startsWith('daily:'))return `Маршрут дня · ${v.slice(6)}`;if(v.startsWith('endless:'))return `Веха бесконечной экспедиции · этап ${Number(v.slice(8))-10000||v.slice(8)}`;return 'Особое открытие экспедиции';},memories=(s.companionMemories||[]).slice(-8).reverse();app.innerHTML=`<section class="screen scroll-page pets-screen">${topbar('Спутники экспедиции')}<div class="page-title"><p class="eyebrow">Вместе интереснее</p><h1>Попутчики и друзья</h1><p class="small">Один друг в пути. До 3 наград и 1 бесплатной буквы в день на всю команду. Дружба меняет рамку портрета.</p><p class="small">${icon('heart','gold')} ${s.hearts} сердец · +${econ().campaignLevelHearts} за новый уровень</p><p class="small companion-journal-note">${icon('book')} ${s.companionMemories?.length||0} записей в общем журнале · активный спутник получает опыт за открытия</p></div><div class="pets-grid">${COMPANIONS.map(p=>{const owned=s.pets.includes(p.id),active=s.activePet===p.id,lvl=s.petLevels[p.id]||1,bond=s.companionBondXp?.[p.id]||0,bondPct=Math.min(100,bond/100*100);return `<article class="pet-card friendship-${lvl} ${active?'active':''} ${owned?'':'locked'}"><img src="${petImage(p)}" alt="${p.name}" loading="lazy"><h3>${p.name}</h3><p class="small">${ABILITIES[p.id]?.text||'Ваш попутчик'}${owned?` · дружба ${lvl}/5`:''}${owned?`<span class="small bond-copy">${companionBondText(p.id,lvl)}</span><span class="bond-unlock">${companionUnlockText(lvl)}</span><span class="bond-meter"><i style="width:${bondPct}%"></i></span><span class="bond-meter-label">Связь ${bond} / 100</span>`:''}</p>${btn(owned?'pet-select':'pet-buy',owned?(active?'Ваш спутник':'Взять с собой'):`Открыть · ${p.cost} ♥`,owned&&active?'check':'','secondary',`data-id="${p.id}" ${active?'disabled':''}`)}${owned&&lvl<5?btn('pet-upgrade',`Дружба ${lvl+1}/5 · ${config.companions.upgradeCosts[lvl-1]} ♥`,'','secondary',`data-id="${p.id}"`):''}</article>`;}).join('')}</div><section class="companion-memories"><div class="row between"><h2>Полевые воспоминания</h2><span class="small">${memories.length}/8</span></div>${memories.length?`<ul>${memories.map(v=>`<li>${icon('complete')}<span>${memoryLabel(v)}</span></li>`).join('')}</ul>`:'<p class="small">Первые записи появятся после завершения главы или особой вехи.</p>'}</section></section>`;if(prevScroll>0){const sc=document.querySelector('.pets-screen');queueMicrotask(()=>{sc.scrollTop=Math.min(prevScroll,sc.scrollHeight-sc.clientHeight);});}
}

 function petAction(action,id){const p=COMPANIONS.find(p=>p.id===id);if(!p)return;const s=state(),config=getConfig();if(action==='pet-select'&&s.pets.includes(id)){s.activePet=id;save();petsPage();return;}if(action==='pet-buy'){if(s.pets.includes(id))return;if(s.hearts<p.cost){toast('Собирайте сердца за новые уровни и цели');return;}modal('buy-pet',`<img class="pet-modal-image" src="${petImage(p)}" alt=""><h2>${p.name}</h2><p>Станет вашим спутником. ${ABILITIES[p.id]?.text}. Не больше трёх наград и одной бесплатной буквы в день на всех спутников вместе.</p>${btn('pet-confirm',`Пригласить · ${p.cost} ♥`,'heart','primary wide',`data-id="${p.id}"`)}`);return;}if(action==='pet-confirm'&&!s.pets.includes(id)&&s.hearts>=p.cost){s.hearts-=p.cost;s.pets.push(id);s.activePet=id;s.petLevels[id]=1;save();petsPage();toast('Новый друг присоединился к экспедиции!');}if(action==='pet-upgrade'&&s.pets.includes(id)){const lvl=s.petLevels[id]||1,cost=config.companions.upgradeCosts[lvl-1];if(!cost)return;if(s.hearts<cost){toast('Пока не хватает сердец');return;}s.hearts-=cost;s.petLevels[id]=lvl+1;save();petsPage();toast('Новый уровень дружбы! Обновлена рамка спутника.');}}

 function showSettings(){modal('settings',`<p class="eyebrow">Ваш ритм</p><h2>Настройки</h2>${[['sound','Звуки игры','Мягкий отклик на каждую букву'],['music','Фоновая мелодия','Спокойные музыкальные переливы'],['motion','Анимации','Движение и праздничные эффекты'],['companionReactions','Реакции спутников','Фразы и эмоции активного питомца']].map(([key,title,desc])=>`<div class="settings-row"><div><strong>${title}</strong><p>${desc}</p></div><button class="switch ${state().settings[key]?'on':''}" role="switch" aria-checked="${state().settings[key]}" aria-label="${title}" data-action="toggle" data-id="${key}"></button></div>`).join('')}<p class="small settings-save-note">Язык: русский<br>${platform.cloudReady?'Прогресс сохраняется на устройстве и в облаке Яндекс Игр.':store.persistent?'Прогресс сохраняется на этом устройстве.':'Сохранение на устройстве недоступно в этом режиме браузера.'}</p>${platform.sdk&&!platform.cloudReady?btn('sync','Восстановить облачное сохранение','compass','secondary wide'):''}${btn('help','Как играть','help','secondary wide')}${btn('close','Готово','check','primary wide')}<p class="small center version-note">Слова: Забытая Экспедиция · 5.3.4</p>`,{cls:'panel-md'});}

 function help(){modal('help',`<div class="surface-body"><p class="eyebrow">Всё начинается с одного слова</p><h2>Соединяйте. Открывайте.</h2><div class="help-example"><span>К</span><span>О</span><span>Т</span></div><div class="help-step"><b>01</b><p>Проведите по буквам, чтобы составить слово. Отпустите палец — слово появится в кроссворде.</p></div><div class="help-step"><b>02</b><p>Можно нажимать буквы по очереди, а затем нажать на собранное слово. На компьютере работает клавиатура: буквы, Enter и Backspace.</p></div><div class="help-step"><b>03</b><p>Ищите существительные от 3 букв. Каждую букву круга можно использовать один раз. Е и Ё считаются одной буквой.</p></div><div class="help-step"><b>✦</b><p>Лишние слова пополняют сундук. Перемешивание бесплатно. Три звезды — за решение без подсказок, ошибок бояться не нужно.</p></div></div><div class="surface-footer">${btn('close','Всё понятно','check','primary wide')}</div>`,{cls:'surface panel-md'});}

 function onboarding(){modal('onboarding',`${icon('compass','hero-icon')}<p class="eyebrow">Добро пожаловать в экспедицию</p><h2>Откройте первое слово</h2><p>Нажмите буквы по очереди или проведите по ним пальцем — затем отправьте собранное слово. После 8-го уровня вас встретит первый спутник, а новые маршруты будут открываться постепенно.</p><div class="reward-box"><div>${icon('daily')}<span class="small">Маршрут дня</span></div><div>${icon('companions')}<span class="small">12 спутников</span></div><div>${icon('gift')}<span class="small">Бонусы</span></div></div>${btn('onboarding-close','Начать путешествие','arrow','primary wide')}${btn('help','Посмотреть правила','help','secondary wide')}`,{close:false,center:true});}

 function profile(){const s=state(),owned=new Set(s.inventory);const unlocked=c=>captainIsUnlocked(c,s);const profileTitle=s.profile.title==='title-pathfinder'?'Следопыт':s.profile.title==='title-keeper'?'Хранитель слов':captainTitle();const profilePortrait=s.profile.portrait==='portrait-default'?captainAvatar():shopIcon(s.profile.portrait);modal('profile',`${icon('user','hero-icon')}<p class="eyebrow">Личная карточка экспедиции</p><h2>Профиль капитана</h2><div class="profile-card ${s.profile.frame}"><div class="profile-avatar">${profilePortrait}</div><div><b>${profileTitle}</b><span class="small captain-motto">${captainMotto?.()||''}</span><span class="small">${s.completed.length} пройдено · ${starsTotal(s)} собрано</span><span class="small">${s.pets.length}/12 спутников · этап ${s.endless.best}</span><span class="small">Ранг бесконечной экспедиции: ${endlessRank(s.endless.best)}</span></div></div><p class="eyebrow profile-label">Выберите капитана</p><div class="profile-options captain-options">${CAPTAINS.map(c=>{const open=unlocked(c),active=s.activeCaptain===c.id;return `<button class="profile-option ${active?'selected':''} ${open?'':'locked'}" data-action="captain-select" data-id="${c.id}" ${open?'':'disabled'}>${c.asset?`<img class="captain-option-image" src="${c.asset}" alt="">`:icon(c.icon)}<span>${c.title}</span><small>${open?(active?'Выбран':c.condition):c.condition}</small></button>`;}).join('')}</div>${petCard()}${btn('pets','Открыть спутников','companions','secondary wide')}${btn('close','Готово','check','primary wide')}`,{cls:'panel-lg'});}

 function wallet(){analytics.send('feature_open',{feature:'wallet'});const c=econ(),remaining=rewardedRemaining('ad-coins'),adOk=platform.sdk?.adv&&remaining>0;modal('wallet',`${icon('rewardCoin','hero-icon')}<h2>Монеты искателя</h2><p>У вас <b>${state().coins} монет</b>. Подсказка открывает одну букву за ${c.letterHintCost} ◉, целое слово — за ${c.wordHintCost} ◉.</p><div class="reward-box"><p>Монеты дают уровни, бонусные слова и цели. В сундуке бонусов радар включается за монеты — столько раз, сколько захотите, цену всегда видно на игровом экране.</p></div>${adOk?btn('ad-coins',`Реклама · +${rewardedCfg().coins} монет · ${remaining} осталось`,'video','primary wide'):''}${platform.sdk?.adv&&remaining===0?'<p class="small center">Лимит рекламных монет на сегодня исчерпан.</p>':''}${btn('shop','Магазин экспедиции','shop',adOk?'secondary wide':'primary wide')}${btn('gift','Ежедневный подарок','gift','secondary wide')}${btn('goals','Награды за цели','goals','secondary wide')}`);}

 const CATALOG_PRICES={
  expedition_no_ads:'149 ₽',
  expedition_starter:'199 ₽',
  expedition_coins_500:'79 ₽',
  expedition_coins_1200:'159 ₽',
  expedition_coins_3000:'349 ₽',
  expedition_coins_7500:'699 ₽',
 expedition_coins_18000:'1299 ₽'
 };
  function moneyLabel(p,id){
  if(!p)return CATALOG_PRICES[id]||'Цена в каталоге';
  const rawPrice=String(p.price||p.formattedPrice||((p.priceValue&&p.priceCurrencyCode)?`${p.priceValue} ${p.priceCurrencyCode}`:'Цена в каталоге'));
  const normalizedPrice=rawPrice.replace(/\bRUB\b/gi,'₽').replace(/\s{2,}/g,' ');
  const price=escapeHTML(normalizedPrice);
  let image='';try{const src=typeof p.getPriceCurrencyImage==='function'?p.getPriceCurrencyImage('small'):'';if(src)image=` <img class="portal-currency-icon" src="${escapeHTML(src)}" alt="${escapeHTML(p.priceCurrencyCode||'')}">`;}catch{}
   return `${price}${image}`;
  }
  function paidCatalogBlock(noAds,starter,noAdsId,starterId){
   if(!noAds&&!starter)return '';
   const noAdsOffer=noAds?`<article class="real-offer ${state().adsRemoved?'is-complete':''}"><div class="real-offer-icon">${shopIcon('no_ads')}</div><div class="real-offer-copy"><b>Убрать рекламу</b><span>Отключает межуровневую рекламу. Подсказки, бонусы и награды остаются доступны.</span><small>${moneyLabel(noAds,noAdsId)}</small></div>${btn('purchase-no-ads',state().adsRemoved?'Реклама отключена':'Купить','shield','secondary',state().adsRemoved?'disabled':'')}</article>`:'';
   const starterOffer=starter?`<article class="real-offer ${state().starterClaimed?'is-complete':''}"><div class="real-offer-icon">${shopIcon('starter_explorer')}</div><div class="real-offer-copy"><b>Набор исследователя</b><span>300 монет · 3 бесплатные подсказки · спутник Сова-эрудит.</span><small>${moneyLabel(starter,starterId)}</small></div>${btn('purchase-starter',state().starterClaimed?'Набор получен':'Купить','gift','secondary',state().starterClaimed?'disabled':'')}</article>`:'';
   return `<section class="real-offers"><h3>Покупки за реальные деньги</h3><p class="small real-offers-note">Разовые предложения подключаются через каталог Яндекс Игр.</p>${noAdsOffer}${starterOffer}${btn('restore-purchases','Восстановить покупки','cloud','secondary wide')}</section>`;
  }
  function shopConfirm(id){const item=SHOP_ITEMS.find(entry=>entry.id===id);if(!item||state().inventory.includes(id))return;const enough=state().coins>=item.cost;modal('shop-confirm',`<div class="shop-confirm-preview">${shopIcon(item.id)}</div><p class="eyebrow">Находка для экспедиции</p><h2>${item.title}</h2><p>${item.description}. После покупки предмет навсегда появится в вашем дневнике.</p><div class="shop-confirm-price"><span>Стоимость</span><b>${item.cost} ${icon('expeditionCoin','price-coin')}</b></div>${enough?btn('shop-confirm',`Подтвердить · ${item.cost} ${icon('expeditionCoin','price-coin')}`,'check','primary wide',`data-id="${item.id}"`):`<p class="small shop-insufficient">Не хватает ${item.cost-state().coins} монет. Заработайте их в уровнях, целях или ежедневном подарке.</p>`}${btn('shop','Вернуться в магазин','arrow','secondary wide')}`,{cls:'panel-md'});}
  function shopPurchase(id){const result=buyShopItem(store,id);if(!result.ok){toast('Пока не хватает монет');return;}save();analytics.send('shop_purchase',{item:result.item.id,currency:'coins',cost:result.item.cost});shopExpanded();toast(`${result.item.title} добавлен в дневник`);}
  async function coinPurchase(id){const result=await commerceBuy(id);if(!result.ok){toast(result.reason==='cloud-unavailable'?'Сначала включите облачное сохранение Яндекс Игр.':result.reason==='cancel'?'Покупка отменена':'Не удалось подтвердить покупку');return;}shopExpanded();toast(`Зачислено ${result.amount||0} монет`);}
  function shop(tab='all'){analytics.send('shop_open');const owned=new Set(state().inventory),groups=[['Капитаны и профиль','profile',['captain-lighthouse','captain-north']],['Оформление экспедиции','style',['camp-lantern','letters-seaglass']]],visible=tab==='all'?groups:groups.filter(([,kind])=>kind===tab);const itemCard=item=>{if(!item)return '';const have=owned.has(item.id),enough=state().coins>=item.cost;return `<article class="shop-item ${have?'is-owned':''}"><div class="shop-item-icon">${shopIcon(item.id)}</div><div class="shop-item-copy"><b>${item.title}</b><span class="small">${item.description}</span></div><div class="shop-item-action">${have?`<span class="shop-owned">${icon('check')} Открыто</span>`:btn('shop-buy',enough?`${item.cost} ${icon('expeditionCoin','price-coin')}`:'Не хватает монет','','primary',`data-id="${item.id}"`)}</div></article>`;};const noAdsId=getConfig().catalog.no_ads,starterId=getConfig().catalog.starter_explorer,noAds=commerceProduct?.(noAdsId),starter=commerceProduct?.(starterId);const paid=platform.sdk&&commerceAvailable()&&(noAds||starter);modal('shop',`<div class="shop-hero"><div class="shop-hero-icon">${icon('shop')}</div><div><p class="eyebrow">Личные находки</p><h2>Магазин экспедиции</h2><p class="small">Капитаны и оформление лагеря</p></div></div><div class="shop-wallet"><span>${icon('expeditionCoin')} Ваши монеты</span><b>${state().coins}</b></div><div class="shop-tabs" role="tablist">${[['all','Все находки'],['profile','Профиль'],['style','Оформление']].map(([id,label])=>`<button class="shop-tab ${tab===id?'active':''}" data-action="shop-tab" data-id="${id}" role="tab" aria-selected="${tab===id}">${label}</button>`).join('')}</div>${visible.map(([title,,ids])=>`<section class="shop-group"><h3>${title}</h3><div class="shop-list">${ids.map(id=>itemCard(SHOP_ITEMS.find(item=>item.id===id))).join('')}</div></section>`).join('')}${paid?paidCatalogBlock(noAds,starter,noAdsId,starterId):''}`,{cls:'panel-lg'});}

 const goalValue=g=>economyGoalValue(g,state(),starsTotal);
 const goalCategory=g=>g.type==='levels'?'Путь':g.type==='words'?'Слова':g.type==='bonus'?'Тайны':g.type==='chapters'?'Находки':g.type==='captains'||g.type==='pets'?'Команда':g.type==='endless'?'За гранью карты':'Серии';
 const rankFor=s=>s.completed.length>=304?'Легенда экспедиции':s.completed.length>=200?'Хранитель маршрутов':s.completed.length>=100?'Исследователь':s.completed.length>=40?'Картограф':s.completed.length>=8?'Следопыт':'Новичок экспедиции';
 function goalsJournal(filter='all'){const s=state(),done=GOALS.filter(g=>s.goals.includes(g.id)),ready=GOALS.filter(g=>!s.goals.includes(g.id)&&goalValue(g)>=g.need),available=GOALS.filter(g=>!s.goals.includes(g.id)&&goalValue(g)<g.need&&!(g.type==='endless'&&s.completed.length<304)),next=available.sort((a,b)=>(goalValue(b)/b.need)-(goalValue(a)/a.need))[0]||GOALS.find(g=>!s.goals.includes(g.id))||GOALS[0],rank=rankFor(s),pct=Math.min(100,s.completed.length/304*100),groups=[...new Set(GOALS.map(goalCategory))],visibleGroups=filter==='all'?groups:groups.filter(g=>g===filter);const goalRow=g=>{const v=goalValue(g),complete=s.goals.includes(g.id),can=!complete&&v>=g.need;return `<article class="journal-goal ${complete?'is-done':''} ${can?'is-ready':''}"><div class="journal-goal-icon">${complete?icon('goalSeal'):goalIcon(g)}</div><div class="journal-goal-copy"><b>${g.title}</b><span>${g.description}</span><small>${Math.min(v,g.need)} / ${g.need}</small></div><div class="journal-goal-reward"><strong>${g.reward}</strong><small>монет</small>${can?btn('goal-claim','Забрать','check','primary',`data-id="${g.id}"`):complete?'<span>Получено</span>':''}</div></article>`;};modal('goals',`<div class="goals-journal-hero"><div class="goals-journal-seal">${icon('goalSeal')}</div><div><p class="eyebrow">Личный журнал находок</p><h2>Цели экспедиции</h2><p class="small">Ваше звание: <b>${rank}</b></p></div></div><div class="rank-progress"><div class="row between"><span>Путь до легенды</span><b>${s.completed.length} / 304</b></div><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div></div><div class="next-goal"><div class="next-goal-label">${ready.length?'Готово к получению':'Следующая веха'}</div><h3>${ready[0]?.title||next.title}</h3><p>${ready.length?'Награда ждёт вас в журнале':next.description}</p><div class="row between"><span class="small">${ready.length?`Можно забрать ${ready.length} нагр.`:`${Math.min(goalValue(next),next.need)} / ${next.need}`}</span>${ready.length?btn('goal-claim','Забрать награду','check','primary',`data-id="${ready[0].id}"`):''}</div></div><div class="goal-category-tabs" role="tablist" aria-label="Категории целей"><button class="goal-category-chip ${filter==='all'?'active':''}" data-action="goal-tab" data-id="all" role="tab" aria-selected="${filter==='all'}">Все цели</button>${groups.map(g=>`<button class="goal-category-chip ${filter===g?'active':''}" data-action="goal-tab" data-id="${g}" role="tab" aria-selected="${filter===g}">${g}</button>`).join('')}</div><div class="journal-goals-list">${visibleGroups.length?visibleGroups.map(group=>`<section class="journal-goal-group"><h3>${group}</h3>${GOALS.filter(g=>goalCategory(g)===group).map(goalRow).join('')}</section>`).join(''):'<p class="small center goals-empty">В этой категории пока нет целей.</p>'}</div>`,{cls:'panel-lg'});}
 const goalIcon=g=>icon(g.type==='levels'?'journey':g.type==='words'?'book':g.type==='bonus'?'spark':g.type==='stars'?'star':g.type==='chapters'?'artifacts':g.type==='captains'?'leaderboard':g.type==='pets'?'companions':g.type==='endless'?'endless':g.type==='streak'?'streak':'achievement');
 function goals(){const s=state(),completed=GOALS.filter(g=>s.goals.includes(g.id)).length,total=GOALS.length;modal('goals',`<div class="goals-hero"><div class="goals-hero-icon">${icon('goals')}</div><div><p class="eyebrow">Долгий путь</p><h2>Цели экспедиции</h2><p class="small">Собрано ${completed} из ${total} наград · ${total-completed} впереди</p></div></div><div class="goals-summary"><span><b>${completed}/${total}</b><small>получено</small></span><div class="progress-track"><div class="progress-fill" style="width:${completed/total*100}%"></div></div><span><b>${GOALS.reduce((a,g)=>a+g.reward,0)} ◉</b><small>всего наград</small></span></div><div class="goals-list">${GOALS.map(g=>{const v=goalValue(g),done=s.goals.includes(g.id),pct=Math.min(100,v/g.need*100);return `<article class="goal-row ${done?'is-done':''} ${v>=g.need&&!done?'is-ready':''}"><div class="goal-main"><div class="goal-icon">${goalIcon(g)}</div><div class="goal-copy"><h3>${g.title}</h3><p>${g.description}</p></div><div class="goal-reward">${done?icon('check'):icon('goalSeal')}<b>${done?'Получено':g.reward}</b></div></div><div class="goal-progress"><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div><span class="small">${Math.min(v,g.need)} / ${g.need}</span>${btn('goal-claim',done?'Получено':v>=g.need?'Забрать':`${g.reward} ◉`,done?'check':'',v>=g.need&&!done?'primary':'secondary',`data-id="${g.id}" ${done||v<g.need?'disabled':''}`)}</div></article>`;}).join('')}</div>`,{cls:'panel-md'});}
 function gift(){const s=state(),today=dateKey(platform.now()),{claimed,streak,reward}=dailyGiftOffer(s,today,previousDay(platform.now()));modal('gift',`${icon('gift','hero-icon')}<p class="eyebrow">Рады новой встрече</p><h2>Подарок путешественнику</h2><p>${claimed?'Сегодняшний подарок уже у вас. Завтра будет новый!':`День ${streak} подряд. Заглядывайте каждый день: подарок растёт до 55 монет.`}</p><div class="reward-box">${icon('rewardCoin')}<strong>+${reward}</strong><span class="small">монет</span></div>${btn('gift-claim',claimed?'Уже получено':'Забрать подарок',claimed?'check':'gift','primary wide',claimed?'disabled':'')}`);}

 function ensureDaily(){const day=dateKey(platform.now());if(ensureDailyState(state(),day))save();return state().daily;}
 function daily(){const d=ensureDaily(),c=econ(),steps=[['След тропы','Первый ориентир'],['Старая карта','Найти подсказку'],['Костёр','Завершить маршрут']];modal('daily',`<div class="daily-hero"><div class="daily-hero-icon">${icon('routeCompass')}</div><div><p class="eyebrow">${new Intl.DateTimeFormat('ru',{day:'numeric',month:'long',timeZone:'UTC'}).format(platform.now())}</p><h2>Маршрут дня</h2><p class="small">Три коротких этапа без таймера</p></div></div><div class="daily-reward-card"><div><span class="small">Награда за полный маршрут</span><b>${c.dailyCoins} ◉ + ${c.dailyHearts} ♥</b></div><span class="small">Серия: ${state().gift.streak||0} дн.</span></div><div class="route-steps">${steps.map((item,n)=>`<div class="route-step ${d.step>n?'done':d.step===n?'current':''}">${icon(d.step>n?'routeComplete':d.step===n?'routeCompass':'locked')}<b>${item[0]}</b><span class="small">${d.step>n?'Пройдено':d.step===n?item[1]:'Закрыто'}</span></div>`).join('')}</div>${btn('daily-start',d.claimed?'Маршрут пройден':d.step?'Продолжить маршрут':'Отправиться','arrow','primary wide',d.claimed?'disabled':'')}<p class="small center route-note">Новый маршрут появится завтра · без таймера</p>`);}

 function weekly(){const s=state(),key=weekKey(platform.now()),cfg=weeklyCfg();if(ensureWeeklyState(s,key))save();const steps=s.weekly.steps;modal('weekly',`${icon('weekly','hero-icon')}<p class="eyebrow">Экспедиция недели</p><h2>${cfg.steps} находок</h2><p>Завершите ${cfg.steps} новых уровней кампании или бесконечной экспедиции за неделю. Это необязательный маршрут без таймеров и ограничений.</p><div class="progress-track"><div class="progress-fill" style="width:${Math.min(100,steps/cfg.steps*100)}%"></div></div><p class="small center">${steps} / ${cfg.steps} завершено</p><div class="reward-box">${icon('gift')}<strong>+${cfg.coins} монет</strong><span class="small">и ${cfg.hearts} ед. сердец</span></div>${btn(steps<cfg.steps?'continue':'weekly-claim',s.weekly.claimed?'Награда получена':steps>=cfg.steps?'Забрать награду':'Продолжить путь','check','primary wide',s.weekly.claimed?'disabled':'')}${btn('leaderboard','Таблица рекордов','leaderboard','secondary wide')}`);}

 async function leaderboard(){const boardId=getConfig().leaderboards.endless,best=state().endless.best;modal('leaderboard',`${icon('leaderboard','hero-icon')}<p class="eyebrow">Бесконечная экспедиция</p><h2>Таблица рекордов</h2><p>Загружаем результаты игроков Яндекс Игр…</p>`,{close:true});if(best>0)void platform.leaderboardSubmit(boardId,best,`best:${best}`);const data=await platform.leaderboardGet(boardId,{quantityTop:10,includeUser:true,quantityAround:2});if(ctx.currentModal()!=='leaderboard')return;const entries=Array.isArray(data?.entries)?data.entries:[];if(entries.length){analytics.send('leaderboard_loaded',{board:boardId,entries:entries.length});modal('leaderboard',`${icon('leaderboard','hero-icon')}<p class="eyebrow">Бесконечная экспедиция</p><h2>Таблица рекордов</h2><p>Рейтинг строится по лучшему пройденному этапу. Покупки и монеты на место не влияют.</p><div class="leaderboard-list">${entries.map((entry,i)=>{const rank=Number.isFinite(entry.rank)?entry.rank+1:i+1,name=escapeHTML(entry.player?.publicName||'Искатель'),score=Math.max(0,Math.floor(Number(entry.score)||0)),self=Number.isFinite(data.userRank)&&entry.rank===data.userRank;return `<div class="leader-row ${self?'self':''}"><b>${rank}</b><span class="leader-avatar">${self?captainAvatar():icon('compass')}</span><div><strong>${name}</strong><small>${self?'Ваш результат':'Игрок Яндекс Игр'}</small></div><em>${score}</em></div>`;}).join('')}</div>${btn('close','Вернуться','arrow','primary wide')}`);return;}analytics.send('leaderboard_fallback',{board:boardId});modal('leaderboard',`${icon('leaderboard','hero-icon')}<p class="eyebrow">Личный рекорд</p><h2>Таблица пока недоступна</h2><p>${best>0?`Ваш лучший этап бесконечной экспедиции: <b>${best}</b>. Он будет отправлен в системный рейтинг, когда лидерборд доступен и игрок авторизован.`:'Завершите основное путешествие, чтобы открыть бесконечную экспедицию и установить первый рекорд.'}</p>${btn('close','Вернуться','arrow','primary wide')}`);}

 function startDaily(){const d=ensureDaily();if(d.claimed)return;const levels=getLevels(),route=dailyRoute(d.day,levels.length);startLevel(route[d.step]+1,'daily');}

 document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const n=el.dataset.action;if(n==='catalog-retry'){e.stopImmediatePropagation();el.disabled=true;el.textContent='Проверяем каталог…';void Promise.resolve(commerceRetry?.()).then(()=>shopExpanded());return;}if(n==='goals'||n==='goal-claim'||n==='goal-tab'||n==='shop-buy'||n==='shop-tab'||n==='shop-confirm'||n==='purchase-coins'){e.stopImmediatePropagation();n==='goals'?goalsJournal():n==='goal-claim'?(claimGoal(state(),el.dataset.id,starsTotal),save(),goalsJournal()):n==='goal-tab'?goalsJournal(el.dataset.id||'all'):n==='shop-buy'?shopConfirm(el.dataset.id):n==='shop-tab'?shop(el.dataset.id||'all'):n==='shop-confirm'?shopPurchase(el.dataset.id):void coinPurchase(el.dataset.id);}},true);
 const coinPacks={
  coins_handful:{base:500,bonus:0,total:500,percent:0},
  coins_pouch:{base:1200,bonus:240,total:1440,percent:20},
  coins_satchel:{base:3000,bonus:750,total:3750,percent:25},
  coins_chest:{base:7500,bonus:2625,total:10125,percent:35},
  coins_expedition:{base:18000,bonus:9000,total:27000,percent:50}
 };
 const coinIds=Object.keys(coinPacks);

 let expandedShopBound=false;
 function shopExpanded(){
  analytics.send('shop_open');
  const owned=new Set(state().inventory),groups=[
   ['Капитаны и профиль',['portrait-owl','portrait-fox','portrait-cartographer','frame-sunset','frame-patina','title-pathfinder','title-keeper','captain-lighthouse','captain-north']],
   ['Оформление экспедиции',['camp-lantern','letters-seaglass']],
   ['Запасы в дорогу',['hint-supply','heart-supply']]
  ];
  const itemCard=item=>{const have=!item.repeatable&&owned.has(item.id),enough=state().coins>=item.cost;return `<article class="shop-item ${have?'is-owned':''}"><div class="shop-item-icon">${shopIcon(item.id)}</div><div class="shop-item-copy"><b>${item.title}</b><span class="small">${item.description}</span></div><div class="shop-item-action">${have?`<span class="shop-owned">${icon('check')} Открыто</span>`:btn('expanded-shop-buy',enough?`${item.cost} ${icon('expeditionCoin','price-coin')}`:'Не хватает монет','','primary',`data-id="${item.id}"`)}</div></article>`;};
 const noAdsId=getConfig().catalog.no_ads,starterId=getConfig().catalog.starter_explorer,noAds=commerceProduct?.(noAdsId),starter=commerceProduct?.(starterId),commerceState=commerceStatus?.()||'idle',paid=platform.sdk&&commerceAvailable()&&(noAds||starter),catalogReady=platform.sdk&&commerceAvailable()&&commerceState==='ready',coinPacksMarkup=catalogReady?`<section class="coin-packs"><h3>Пополнить запас монет</h3><p class="coin-packs-note">Итого — это сумма зачисления. Бонус уже включён и не требует отдельного действия.</p><div class="coin-pack-grid">${coinIds.map((key,i)=>{const id=getConfig().catalog[key],p=commerceProduct?.(id),pack=coinPacks[key];if(!p)return '';const total=pack.total.toLocaleString('ru-RU'),base=pack.base.toLocaleString('ru-RU'),bonus=pack.bonus.toLocaleString('ru-RU'),bonusLine=pack.bonus?`База ${base} + ${bonus} бонус`:`База ${base}`;return `<button class="coin-pack ${i===2?'featured':''}" data-action="purchase-coins" data-id="${id}" aria-label="Получить ${total} монет за ${moneyLabel(p,id)}${pack.percent?`, бонус ${pack.percent} процентов к базовой сумме`:''}"><span class="coin-pack-icon">${shopIcon(key)}</span><strong class="coin-pack-total">${total} <small>монет итого</small></strong><small class="coin-pack-breakdown">${bonusLine}</small><small class="coin-pack-price">${moneyLabel(p,id)}</small>${pack.percent?`<em class="coin-pack-badge">+${pack.percent}% к монетам</em>`:'<em class="coin-pack-badge is-base">Без бонуса</em>'}</button>`;}).join('')}</div></section>`:'',catalogNotice=platform.sdk&&commerceAvailable()&&!paid?((commerceState==='loading'||commerceState==='idle')?'<p class="small catalog-status">Подключаем товары Яндекс Игр…</p>':`<p class="small catalog-status">Платные товары временно недоступны. Проверьте соединение и повторите загрузку.</p>${btn('catalog-retry','Повторить загрузку','cloud','secondary wide')}`):'';
  modal('shop',`<div class="shop-hero"><div class="shop-hero-icon">${icon('shop')}</div><div><p class="eyebrow">Личные находки</p><h2>Магазин экспедиции</h2><p class="small">Оформление, профиль и запасы</p></div></div><div class="shop-wallet"><span>${icon('expeditionCoin')} Ваши монеты</span><b>${state().coins}</b></div>${coinPacksMarkup}${groups.map(([title,ids])=>`<section class="shop-group"><h3>${title}</h3><div class="shop-list">${ids.map(id=>itemCard(SHOP_ITEMS.find(item=>item.id===id))).join('')}</div></section>`).join('')}${catalogNotice}${paid?paidCatalogBlock(noAds,starter,noAdsId,starterId):''}`,{cls:'panel-lg'});
  if(!expandedShopBound){expandedShopBound=true;document.addEventListener('click',e=>{const el=e.target.closest('[data-action="expanded-shop-buy"]');if(!el||el.disabled)return;e.preventDefault();e.stopImmediatePropagation();const result=buyShopItem(store,el.dataset.id);if(!result.ok){toast(result.reason==='owned'?'Уже открыто':'Пока не хватает монет');return;}save();analytics.send('shop_purchase',{item:result.item.id,currency:'coins',cost:result.item.cost,repeatable:!!result.item.repeatable});shopExpanded();toast(result.item.repeatable?`${result.item.title}: запас пополнен`:`${result.item.title} добавлен в дневник`);},true);}
 }
 const baseProfile=profile;
 function profileExpanded(){
  baseProfile();
  const box=document.querySelector('.modal');if(!box)return;
  const s=state(),owned=new Set(s.inventory),choices=[
   ['Портрет',['portrait-default','portrait-owl','portrait-fox','portrait-cartographer']],
   ['Рамка',['frame-default','frame-sunset','frame-patina']],
   ['Титул',['title-default','title-pathfinder','title-keeper']]
  ];
  const labels={'portrait-default':'Стандартный','portrait-owl':'Сова','portrait-fox':'Лис','portrait-cartographer':'Картограф','frame-default':'Стандартная','frame-sunset':'Закат','frame-patina':'Патина','title-default':'Искатель','title-pathfinder':'Следопыт','title-keeper':'Хранитель слов'};
  const optionIcon=id=>id==='portrait-default'?captainAvatar():shopIcon(id);
  const enabled=id=>id.endsWith('default')||owned.has(id);
  const currentKey=title=>title==='Портрет'?'portrait':title==='Рамка'?'frame':'title';
  box.querySelector('.profile-card')?.insertAdjacentHTML('afterend',`<p class="profile-applied-note">Сейчас применено: портрет «${labels[s.profile.portrait]}» · рамка «${labels[s.profile.frame]}» · титул «${labels[s.profile.title]}». Это только визуальное оформление карточки.</p>`);
  box.insertAdjacentHTML('beforeend',`<section class="profile-customization"><p class="eyebrow">Оформление карточки</p><p class="small profile-custom-note">Это косметика профиля: она меняет портрет, рамку и титул в вашей карточке, но не влияет на сложность уровней.</p>${choices.map(([title,ids])=>{const key=currentKey(title);return `<div class="profile-custom-group"><h3>${title}</h3><div class="profile-custom-options">${ids.map(id=>{const selected=s.profile[key]===id;return `<button class="profile-custom-option ${selected?'selected':''}" data-action="profile-set" data-id="${id}" aria-pressed="${selected}" ${enabled(id)?'':'disabled'}>${optionIcon(id)}<span>${labels[id]}</span>${selected?'<small class="profile-custom-state">Выбрано</small>':''}</button>`;}).join('')}</div></div>`;}).join('')}</section>`);
 }
 return {home,mapPage,albumPage,artifact,petsPage,petAction,showSettings,help,onboarding,profile:profileExpanded,wallet,shop:shopExpanded,shopConfirm,goals,gift,daily,weekly,leaderboard,startDaily,ensureDaily};
}
